config/routes.rb
Rails.application.routes.draw do

  resources :recipes

  root 'recipes#index'

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :ingredients
	has_many :directions

	accepts_nested_attributes_for :ingredients, allow_destroy: true
	accepts_nested_attributes_for :directions, allow_destroy: true

	# validates :title, :description, :image, presence: true
	
	has_attached_file :image, styles: { medium: "400x400>", thumb: "100x100>" }, default_url: "images.jpg"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: "Successfully created new recipe"
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: "Successfully deleted recipe"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
	<%= f.text_area :name, input_html: { class: 'form-input form-control'} %>
	<%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
</div>


app/views/recipes/edit.html.erb
<div>
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(@recipe), url: recipes_path, html: { multipart: true } do |f| %>
        <form>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_area :title, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.file_field :image, :class => 'form-control' %>
          </div>
          <%= f.submit "Save", :class => 'btn btn-default' %>
        </form>
      <% end %>
  </div>
</div>

app/views/recipes/index.html.erb
<div>
  <div class="col-md-8 col-md-offset-2">
    <div class="row">
    <% @recipes.each do |recipe| %>
    <!-- <div class="row"> -->
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <%= link_to (image_tag recipe.image.url(:medium)), recipe_path(recipe.id) %>
          <div class="caption">
            <h3><%= recipe.title %></h3>
            <p><%= recipe.description %></p>
            <p><%= link_to 'Show', recipe_path(recipe.id), :class => 'btn btn-primary' %></p>
          </div>
        </div>
      </div>
    <!-- </div> -->
    <% end %>
    </div>

    <%= link_to 'New Recipe', new_recipe_path, :class => 'btn btn-default' %>
  </div>
</div>

app/views/recipes/new.html.erb
<div>
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(@recipe) do |f| %>
        <form>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_area :title, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.file_field :image, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <h3>Ingredients</h3>
            <%= f.fields_for :ingredients do |ingredient| %>
              <%= render 'ingredients_fields', :f => ingredient %>
            <% end %>
            <div class="links">
              <%= link_to_add_association 'Add Ingredients', f, :ingredients, class: 'btn btn-default add-button' %>
            </div>
          </div>
          <%= f.submit "Save", :class => 'btn btn-default' %>
        </form>
      <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div>
	<div class="col-md-8 col-md-offset-2">
		<button type="button" class="btn btn-default"><%= link_to 'Back', root_path %></button><br><br>

		<div class="panel panel-default">
  		<div class="panel-body">
			<%= image_tag @recipe.image.url(:medium) %><br>
			<h2><%= @recipe.title %></h2>
		    <p><%= @recipe.description %></p>
		  </div>
		</div>

		<div class="btn-group" role="group" aria-label="...">
		  	<button type="button" class="btn btn-default"><%= link_to 'Edit', edit_recipe_path(@recipe.id) %></button>
			<button type="button" class="btn btn-default"><%= link_to 'Delete', recipe_path, method: :delete, data: {confirm: 'Are you sure?'} %></button>
		</div>
	</div>
 </div>